site_name: GiselleBot Documentation
repo_url: https://github.com/cycloptux/GiselleBot-Documentation
repo_name: cycloptux/GiselleBot-Documentation
theme:
  name: material
  features:
     - navigation.top
     - navigation.tabs
     - navigation.sections


